version: "3.9"
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "3001:3000"
    command: bash -c "npm run dev"
  
  db:
    image: postgres:14.2
    volumes:
      - ./db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5433:5432"